export const SEARCH_HAS_ERRORED = 'SEARCH_HAS_ERRORED';
export const SEARCH_IS_LOADING = 'SEARCH_IS_LOADING';
export const SEARCH_DATA_SUCCESS = 'SEARCH_DATA_SUCCESS';
export const SEARCH_DATA_FETCH = 'SEARCH_DATA_FETCH';